baseURL = "https://enclosure-developer.github.io/"
languageCode = "en-us"
title = "Enclosure"
theme = "hugograyscale"
#googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    # Provide some metadata for search and indexing services
    description = "Enclosure: 一个多人迷你游戏 | A Multiplayer Mini-game"

[Author]
    name = "Gary Chen"
    email = "chenhhgary@gmail.com"

# [Social]
#     twitter = "stream_running"
